"""
Cuckoo Search (CS) via Lévy flights.

New solutions are generated by Lévy flights around existing nests (heavy
tailed steps scaled by the distance to the best nest); then a fraction
``pa`` of nest components is abandoned and rebuilt from a random mix of
other nests.  Both phases replace greedily.

References
----------
Yang, X.-S. & Deb, S. (2009). Cuckoo search via Lévy flights.
*World Congress on Nature & Biologically Inspired Computing*, 210–214.
"""

from __future__ import annotations

import math

import numpy as np

from ..population import PopulationOptimiser


def levy_steps(shape, beta: float, rng: np.random.Generator) -> np.ndarray:
    """Draw Lévy-distributed steps with Mantegna's algorithm."""
    sigma = (
        math.gamma(1 + beta)
        * math.sin(math.pi * beta / 2)
        / (math.gamma((1 + beta) / 2) * beta * 2 ** ((beta - 1) / 2))
    ) ** (1 / beta)
    u = rng.normal(0.0, sigma, size=shape)
    v = rng.normal(0.0, 1.0, size=shape)
    return u / np.abs(v) ** (1 / beta)


class CuckooSearchOptimiser(PopulationOptimiser):
    """Cuckoo Search for continuous problems.

    Parameters
    ----------
    pa : float
        Discovery (abandonment) probability.  Default 0.25.
    step_scale : float
        Scale of the Lévy flight step.  Default 0.01.
    levy_beta : float
        Lévy exponent in ``(0, 2]``.  Default 1.5.
    **kwargs
        Budget / seed options from :class:`~optim.population.PopulationOptimiser`.
    """

    default_population_size = 25

    def __init__(
        self,
        pa: float = 0.25,
        step_scale: float = 0.01,
        levy_beta: float = 1.5,
        population_size=None,
        **kwargs,
    ) -> None:
        if not 0.0 <= pa <= 1.0:
            raise ValueError("pa must be in [0, 1]")
        self.pa = pa
        self.step_scale = step_scale
        self.levy_beta = levy_beta
        super().__init__(population_size=population_size, **kwargs)

    def _step(self, problem, state, rng):
        n, d = state.X.shape
        best = problem.best_x

        step = self.step_scale * levy_steps((n, d), self.levy_beta, rng) * (state.X - best)
        cand = problem.clip(state.X + step * rng.standard_normal((n, d)))
        self._greedy_replace(state, cand, problem.evaluate(cand))

        if problem.exhausted:
            return
        abandon = rng.random((n, d)) < self.pa
        mix = rng.random((n, 1)) * (state.X[rng.permutation(n)] - state.X[rng.permutation(n)])
        cand = problem.clip(state.X + mix * abandon)
        self._greedy_replace(state, cand, problem.evaluate(cand))
